name: Build Multi-Platform App
on: [push]
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # 这里让它同时在 Windows 和 Mac 环境下跑
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Escape-App-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.zip
